name: untitled_ui_icons
description: "Untitled UI Icons for Flutter"
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/icons/